apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-mxcw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-mxcw
    app.kubernetes.io/part-of: ci1t-830-0003-app
  name: devfile-sample-mxcw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-mxcw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-mxcw
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0003-tenant/ci1t-830-0003-app/devfile-sample-mxcw@sha256:20c110dc2b6ead325cacf9a787e634a2ed0ae15ed45682f2c5085dd9bbd7efbe
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
